### ISSUE TITLE
Method error on meal update

### ISSUE THREAD

**Issue by smoyth** [gather-community/gather#106]
A NameError occurred in meals#update:

  undefined local variable or method `ttl' for #<Meal:0x00007f799e087068>
Did you mean?  title
  app/models/meal.rb:250:in `enough_capacity_for_current_signups'

-------------------------------
Request:
-------------------------------

  * URL        : https://sunward.gather.coop/meals/2453
  * HTTP Method: PATCH
  * IP address : 68.49.166.79
  * Parameters : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"2nRwAh/tRaBu4VqUASH6KoVhIVLzBIQSrYs43kjpBXSxzvB9zXWjUC3s0TKif9YwqCBISMstipqVTLnDPbSwtw==", "meal"=>{"community_boxes"=>{"2"=>"1", "3"=>"1", "1"=>"1"}, "capacity"=>"21", "head_cook_assign_attributes"=>{"id"=>"13050", "user_id"=>"2783"}, "asst_cook_assigns_attributes"=>{"0"=>{"id"=>"13451", "user_id"=>"2582", "_destroy"=>"false"}, "1"=>{"id"=>"13051", "user_id"=>"2787", "_destroy"=>"false"}}, "table_setter_assigns_attributes"=>{"0"=>{"id"=>"", "user_id"=>"", "_destroy"=>"false"}}, "cleaner_assigns_attributes"=>{"0"=>{"id"=>"13052", "user_id"=>"2946", "_destroy"=>"false"}, "1"=>{"id"=>"13053", "user_id"=>"4581", "_destroy"=>"false"}, "2"=>{"id"=>"", "user_id"=>"", "_destroy"=>"false"}}, "title"=>"Shrimp and Grits", "entrees"=>"Shrimp and grits", "side"=>"Collard greens with smoked turkey", "kids"=>"", "dessert"=>"Cinnamon pound cake with whipped cream", "notes"=>"", "allergen_almonds"=>"0", "allergen_bananas"=>"0", "allergen_corn"=>"1", "allergen_dairy"=>"1", "allergen_eggplant"=>"0", "allergen_eggs"=>"0", "allergen_gluten"=>"0", "allergen_peanuts"=>"0", "allergen_pineapple"=>"0", "allergen_shellfish"=>"1", "allergen_soy"=>"0", "allergen_tofu"=>"0", "allergen_tree_nuts"=>"0", "allergen_none"=>"0", "signups_attributes"=>{"0"=>{"household_id"=>"6805", "lines_attributes"=>{"0"=>{"id"=>"66874791", "quantity"=>"1", "item_id"=>"adult_meat"}, "1"=>{"id"=>"49158592", "quantity"=>"1", "item_id"=>"adult_veg"}}, "id"=>"34714"}, "1"=>{"household_id"=>"6019", "lines_attributes"=>{"0"=>{"id"=>"36404673", "quantity"=>"1", "item_id"=>"adult_meat"}}, "id"=>"34769"}, "2"=>{"household_id"=>"5807", "lines_attributes"=>{"0"=>{"id"=>"98085067", "quantity"=>"2", "item_id"=>"adult_meat"}}, "id"=>"34816"}, "3"=>{"household_id"=>"5812", "lines_attributes"=>{"0"=>{"id"=>"57158658", "quantity"=>"1", "item_id"=>"adult_meat"}}, "id"=>"34798"}, "4"=>{"household_id"=>"5786", "lines_attributes"=>{"0"=>{"id"=>"2592890", "quantity"=>"2", "item_id"=>"adult_meat"}}, "id"=>"34806"}, "5"=>{"household_id"=>"5782", "lines_attributes"=>{"0"=>{"id"=>"99020001", "quantity"=>"2", "item_id"=>"adult_meat"}}, "id"=>"33495"}, "6"=>{"household_id"=>"5770", "lines_attributes"=>{"0"=>{"id"=>"99487509", "quantity"=>"1", "item_id"=>"adult_meat"}}, "id"=>"34860"}, "7"=>{"household_id"=>"5784", "lines_attributes"=>{"0"=>{"id"=>"52018420", "quantity"=>"2", "item_id"=>"adult_meat"}}, "id"=>"33982"}, "8"=>{"household_id"=>"6008", "lines_attributes"=>{"0"=>{"id"=>"57223008", "quantity"=>"1", "item_id"=>"adult_meat"}}, "id"=>"34628"}, "9"=>{"household_id"=>"6047", "lines_attributes"=>{"0"=>{"id"=>"41592556", "quantity"=>"2", "item_id"=>"adult_meat"}, "1"=>{"id"=>"57190500", "quantity"=>"1", "item_id"=>"little_kid_meat"}}, "id"=>"34790"}, "10"=>{"household_id"=>"5806", "lines_attributes"=>{"0"=>{"id"=>"33030953", "quantity"=>"1", "item_id"=>"adult_meat"}, "1"=>{"id"=>"50052993", "quantity"=>"1", "item_id"=>"adult_veg"}}, "id"=>"34613"}, "11"=>{"household_id"=>"5804", "lines_attributes"=>{"0"=>{"id"=>"3004318", "quantity"=>"1", "item_id"=>"adult_meat"}}, "id"=>"34786"}, "12"=>{"household_id"=>"5799", "lines_attributes"=>{"0"=>{"id"=>"98301590", "quantity"=>"1", "item_id"=>"adult_meat"}, "1543374544791"=>{"id"=>"", "quantity"=>"0", "item_id"=>"adult_veg"}, "1543374549774"=>{"id"=>"", "quantity"=>"0", "item_id"=>"teen_meat"}}, "id"=>"34921"}, "1543374566261"=>{"household_id"=>"5803", "lines_attributes"=>{"0"=>{"id"=>"", "quantity"=>"1", "item_id"=>"adult_meat"}}}}, "cost_attributes"=>{"ingredient_cost"=>"", "pantry_cost"=>"", "payment_method"=>""}}, "commit"=>"Save", "controller"=>"meals", "action"=>"update", "id"=>"2453"}
  * Timestamp  : 2018-11-27 22:12:00 -0500
  * Server : ip-172-31-26-230
  * Rails root : /u/apps/gather/releases/20181126193432
  * Process: 24269

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"d73051e3c4dfe1edf098651a1207dad7",
   "warden.user.user.key"=>[[2783], ""],
   "user_return_to"=>"https://sunward.gather.coop/meals/2453",
   "lenses"=>
    {"version"=>4,
     "_global"=>{},
     "users"=>{"index"=>{}},
     "meals"=>{"index"=>{}}},
   "_csrf_token"=>"a7qAf9KY5vBDDYumo14sGi1BaRo4KQ6IOMeBHXVdtcM="}

-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                                 : 8709
  * CONTENT_TYPE                                   : application/x-www-form-urlencoded
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.5
  * HTTP_COOKIE                                    : [FILTERED]
  * HTTP_HOST                                      : sunward.gather.coop
  * HTTP_REFERER                                   : https://sunward.gather.coop/meals/2453/edit
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
  * HTTP_VERSION                                   : HTTP/1.1
  * ORIGINAL_FULLPATH                              : /meals/2453
  * ORIGINAL_SCRIPT_NAME                           : 
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PATH_INFO                                      : /meals/2453
  * QUERY_STRING                                   : 
  * REMOTE_ADDR                                    : 68.49.166.79
  * REMOTE_PORT                                    : 60116
  * REQUEST_METHOD                                 : PATCH
  * REQUEST_URI                                    : /meals/2453
  * ROUTES_47001614771760_SCRIPT_NAME              : 
  * SCRIPT_NAME                                    : 
  * SERVER_NAME                                    : sunward.gather.coop
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.10.2 Phusion_Passenger/5.1.1
  * action_controller.instance                     : #<MealsController:0x00007f799e229d80>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0000557ed1a755d0>
  * action_dispatch.cookies                        : [FILTERED]
  * action_dispatch.cookies_digest                 : [FILTERED]
  * action_dispatch.cookies_serializer             : [FILTERED]
  * action_dispatch.encrypted_cookie_salt          : [FILTERED]
  * action_dispatch.encrypted_signed_cookie_salt   : [FILTERED]
  * action_dispatch.http_auth_salt                 : [FILTERED]
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000557ed7b63658>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000557ed50777f0>
  * action_dispatch.parameter_filter               : [:password, :session, :warden, :secret, :salt, :cookie, :csrf]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 68.49.166.79
  * action_dispatch.request.content_type           : application/x-www-form-urlencoded
  * action_dispatch.request.formats                : [#<Mime::Type:0x0000557ed1284fb0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=3953830304184418474>]
  * action_dispatch.request.parameters             : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"2nRwAh/tRaBu4VqUASH6KoVhIVLzBIQSrYs43kjpBXSxzvB9zXWjUC3s0TKif9YwqCBISMstipqVTLnDPbSwtw==", "meal"=>{"community_boxes"=>{"2"=>"1", "3"=>"1", "1"=>"1"}, "capacity"=>"21", "head_cook_assign_attributes"=>{"id"=>"13050", "user_id"=>"2783"}, "asst_c...
  * action_dispatch.request.path_parameters        : {:controller=>"meals", :action=>"update", :id=>"2453"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"2nRwAh/tRaBu4VqUASH6KoVhIVLzBIQSrYs43kjpBXSxzvB9zXWjUC3s0TKif9YwqCBISMstipqVTLnDPbSwtw==", "meal"=>{"community_boxes"=>{"2"=>"1", "3"=>"1", "1"=>"1"}, "capacity"=>"21", "head_cook_assign_attributes"=>{"id"=>"13050", "user_id"=>"2783"}, "asst_c...
  * action_dispatch.request.unsigned_session_cookie: [FILTERED]
  * action_dispatch.request_id                     : dcaee003-51af-4b20-a919-120fb2c0f3b3
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0000557ed51acc60>
  * action_dispatch.secret_key_base                : [FILTERED]
  * action_dispatch.secret_token                   : [FILTERED]
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : [FILTERED]
  * exception_notifier.exception_data              : {:community=>{:id=>3, :name=>"Sunward"}, :user=>{:id=>2783, :name=>"Maggie Anderson", :email=>"maggie@sunward.org", :google_email=>"maggiemagic2u@gmail.com", :impersonating_id=>nil}}
  * rack.errors                                    : #<IO:0x0000557ed0a79848>
  * rack.hijack                                    : #<Proc:0x00007f799e2dfba8@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00007f799e2dfdd8>
  * rack.methodoverride.original_method            : POST
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : [FILTERED]
  * rack.request.cookie_string                     : [FILTERED]
  * rack.request.form_hash                         : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"2nRwAh/tRaBu4VqUASH6KoVhIVLzBIQSrYs43kjpBXSxzvB9zXWjUC3s0TKif9YwqCBISMstipqVTLnDPbSwtw==", "meal"=>{"community_boxes"=>{"2"=>"1", "3"=>"1", "1"=>"1"}, "capacity"=>"21", "head_cook_assign_attributes"=>{"id"=>"13050", "user_id"=>"2783"}, "asst_c...
  * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x00007f799e2dfdd8>
  * rack.request.form_vars                         : [FILTERED]
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      : 
  * rack.run_once                                  : false
  * rack.session                                   : [FILTERED]
  * rack.session.options                           : [FILTERED]
  * rack.tempfiles                                 : []
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : [FILTERED]

-------------------------------
Backtrace:
-------------------------------

  app/models/meal.rb:250:in `enough_capacity_for_current_signups'
  app/controllers/meals_controller.rb:90:in `update'
  lib/disable_tenant_scoping.rb:18:in `call'

-------------------------------
Data:
-------------------------------

  * data: {:community=>{:id=>3, :name=>"Sunward"},
   :user=>
    {:id=>2783,
     :name=>"Maggie Anderson",
     :email=>"maggie@sunward.org",
     :google_email=>"maggiemagic2u@gmail.com",
     :impersonating_id=>nil}}

_Originally created by **Tom Smyth** at **2018-12-05 09:31**, migrated from [redmine-#9176](https://redmine.sassafras.coop/issues/9176)_

**Comment by smoyth** [comment]
* **Version** set to _6.2_

_By **Tom Smyth** at **2018-12-16 23:05**_

**Comment by smoyth** [comment]
* **Status** changed from _New_ to _Closed_
  *  **Version** changed from _6.2_ to _6.1_

_By **Tom Smyth** at **2018-12-18 15:24**_
