### ISSUE TITLE
Household update not working for non-admins

### ISSUE THREAD

**Issue by smoyth** [gather-community/gather#297]
Add a feature spec, this is a bad one

An ActionView::Template::Error occurred in households#update:

  undefined method `abbrv' for nil:NilClass
  app/decorators/application_decorator.rb:9:in `cmty_prefix'

-------------------------------
Request:
-------------------------------

  * URL        : https://touchstone.gather.coop/households/5761
  * HTTP Method: PATCH
  * IP address : 68.34.51.166
  * Parameters : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"CdMDukeSehJAIEAPyiPSnyR1CgqAd2rjNSWqa7HW/DG8UzJmeh5j6jgFGizbgqJbk+d1iZiVyWgGbFEGBs1Brw==", "household"=>{"name"=>"TS: TS: TS: TS: Kolongowski", "garage_nums"=>"", "vehicles_attributes"=>{"0"=>{"id"=>"19", "_destroy"=>"false", "make"=>"Jeep", "model"=>"Grand Cherokee", "color"=>"White"}, "1"=>{"id"=>"20", "_destroy"=>"false", "make"=>"Honda", "model"=>"Odyssey", "color"=>"Maroon"}}, "emergency_contacts_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"false", "name"=>"Sarah Bush", "relationship"=>"Whitney's Mom", "main_phone"=>"734-846-8861", "location"=>"Livonia, MI", "alt_phone"=>"", "email"=>"sbushmail@gmail.com"}}}, "commit"=>"Update Household", "controller"=>"households", "action"=>"update", "id"=>"5761"}
  * Timestamp  : 2017-06-17 22:29:37 -0400
  * action_controller.instance                     : #<HouseholdsController:0x007f8b80caf248>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0055a48f8b7548>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f8b80ca2ea8>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             : json
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0055a4911c6570>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0055a492c89498>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 68.34.51.166
  * action_dispatch.request.content_type           : application/x-www-form-urlencoded
  * action_dispatch.request.flash_hash             : #<ActionDispatch::Flash::FlashHash:0x0055a495b7d718>
  * action_dispatch.request.formats                : [#<Mime::Type:0x0055a4912017b0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">]
  * action_dispatch.request.parameters             : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"CdMDukeSehJAIEAPyiPSnyR1CgqAd2rjNSWqa7HW/DG8UzJmeh5j6jgFGizbgqJbk+d1iZiVyWgGbFEGBs1Brw==", "household"=>{"name"=>"TS: TS: TS: TS: Kolongowski", "garage_nums"=>"", "vehicles_attributes"=>{"0"=>{"id"=>"19", "_destroy"=>"false", "make"=>"Jeep", "model"=>"Grand Cherokee", "color"=>"White"}, "1"=>{"id"=>"20", "_destroy"=>"false", "make"=>"Honda", "model"=>"Odyssey", "color"=>"Maroon"}}, "emergency_contacts_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"false", "name"=>"Sarah Bush", "relationship"=>"Whitney's Mom", "main_phone"=>"734-846-8861", "location"=>"Livonia, MI", "alt_phone"=>"", "email"=>"sbushmail@gmail.com"}}}, "commit"=>"Update Household", "controller"=>"households", "action"=>"update", "id"=>"5761"}
  * action_dispatch.request.path_parameters        : {:controller=>"households", :action=>"update", :id=>"5761"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"CdMDukeSehJAIEAPyiPSnyR1CgqAd2rjNSWqa7HW/DG8UzJmeh5j6jgFGizbgqJbk+d1iZiVyWgGbFEGBs1Brw==", "household"=>{"name"=>"TS: TS: TS: TS: Kolongowski", "garage_nums"=>"", "vehicles_attributes"=>{"0"=>{"id"=>"19", "_destroy"=>"false", "make"=>"Jeep", "model"=>"Grand Cherokee", "color"=>"White"}, "1"=>{"id"=>"20", "_destroy"=>"false", "make"=>"Honda", "model"=>"Odyssey", "color"=>"Maroon"}}, "emergency_contacts_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"false", "name"=>"Sarah Bush", "relationship"=>"Whitney's Mom", "main_phone"=>"734-846-8861", "location"=>"Livonia, MI", "alt_phone"=>"", "email"=>"sbushmail@gmail.com"}}}, "commit"=>"Update Household"}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"d2ada427c455a3e9f8bfcec22b49f777", "warden.user.user.key"=>[[2577], ""], "user_return_to"=>"https://touchstone.gather.coop/households/5761/edit", "lenses"=>{"version"=>2, "users"=>{"index"=>{}}}, "_csrf_token"=>"tYAx3D2MGfh4JVojEaFwxLeSf4MY4qOLM0n7bbcbvZ4="}
  * action_dispatch.request_id                     : 7fe9c367-c11a-4f66-b9df-0da33cdc7124
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0055a492ce9280>
  * action_dispatch.secret_key_base                : efe289ca3dd6256cdffa00bcf890d12127a4cd33f7556d76ea7d93dd9dbb307daa830ddd29cbdd11948cdc1919b7ed77525100cafb36cb6dd36246f5881034ba
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x0055a48f149540>
  * rack.hijack                                    : #<Proc:0x007f8b80cbcfd8@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f8b80cbd398>
  * rack.methodoverride.original_method            : POST
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"_gather_session"=>"cUZYZ0k1ck1BU0IzcmMzUHlOTzhqUktJQk5RRG1qVFlRQld1T0w3M0o2aUFWdGJYUlczc1pROURYZFVSNWtxYlFKa21GbjY5N3ZiekVEcWwycEhaTmY4Z3NoaEljZ3h6bmJuZ1B6OUZpenlaTXdVMEtrRU5BV3lvamdBYkFFc3VIeG8rQVVDcU0raG55UHd6eXZoVVM1UnRuVEFPalRySVE0eGgxZUlWdmdMRlQxWk9xQ3ZKd1BCcCtIdXdudXQrMDkyU3NRYlIrQWVRejlPZU1oS2lOMFZpTW9FMlBNRmxsL283L3UvbU0yNERsWW5FWVlzeEt3akFDSHF1S0d3Y0FkS0ppVng1TlRIQmZaV09JTTlzanMrQmwrVFZhNmZ6RWswdk9SWkV0a0NBZDEvazA5Vyt6ZlQ2a2dFRWpiUUZJUW1LVFF2K25hdWRsd3B5bkp0S2xDUzU0UmJvZTlYNHpyVTVIUnBOR1dBPS0td1c1Rk5aSU1RZ2JQTXNSc1R0Slladz09--aaa889807672d24c43321ed7e7b1bd3ddb2039f8"}
  * rack.request.cookie_string                     : _gather_session=cUZYZ0k1ck1BU0IzcmMzUHlOTzhqUktJQk5RRG1qVFlRQld1T0w3M0o2aUFWdGJYUlczc1pROURYZFVSNWtxYlFKa21GbjY5N3ZiekVEcWwycEhaTmY4Z3NoaEljZ3h6bmJuZ1B6OUZpenlaTXdVMEtrRU5BV3lvamdBYkFFc3VIeG8rQVVDcU0raG55UHd6eXZoVVM1UnRuVEFPalRySVE0eGgxZUlWdmdMRlQxWk9xQ3ZKd1BCcCtIdXdudXQrMDkyU3NRYlIrQWVRejlPZU1oS2lOMFZpTW9FMlBNRmxsL283L3UvbU0yNERsWW5FWVlzeEt3akFDSHF1S0d3Y0FkS0ppVng1TlRIQmZaV09JTTlzanMrQmwrVFZhNmZ6RWswdk9SWkV0a0NBZDEvazA5Vyt6ZlQ2a2dFRWpiUUZJUW1LVFF2K25hdWRsd3B5bkp0S2xDUzU0UmJvZTlYNHpyVTVIUnBOR1dBPS0td1c1Rk5aSU1RZ2JQTXNSc1R0Slladz09--aaa889807672d24c43321ed7e7b1bd3ddb2039f8
  * rack.request.form_hash                         : {"utf8"=>"?", "_method"=>"patch", "authenticity_token"=>"CdMDukeSehJAIEAPyiPSnyR1CgqAd2rjNSWqa7HW/DG8UzJmeh5j6jgFGizbgqJbk+d1iZiVyWgGbFEGBs1Brw==", "household"=>{"name"=>"TS: TS: TS: TS: Kolongowski", "garage_nums"=>"", "vehicles_attributes"=>{"0"=>{"id"=>"19", "_destroy"=>"false", "make"=>"Jeep", "model"=>"Grand Cherokee", "color"=>"White"}, "1"=>{"id"=>"20", "_destroy"=>"false", "make"=>"Honda", "model"=>"Odyssey", "color"=>"Maroon"}}, "emergency_contacts_attributes"=>{"0"=>{"id"=>"", "_destroy"=>"false", "name"=>"Sarah Bush", "relationship"=>"Whitney's Mom", "main_phone"=>"734-846-8861", "location"=>"Livonia, MI", "alt_phone"=>"", "email"=>"sbushmail@gmail.com"}}}, "commit"=>"Update Household"}
  * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x007f8b80cbd398>
  * rack.request.form_vars                         : [FILTERED]
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f8b80cb64d0>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f8b80cb63e0>
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:70118568997020 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x0055a49337f888>}

-------------------------------
Backtrace:
-------------------------------

  app/decorators/application_decorator.rb:9:in `cmty_prefix'
  app/decorators/household_decorator.rb:6:in `name'
  app/views/households/edit.html.erb:1:in `block in _app_views_households_edit_html_erb__1099396562214718293_70118538196100'
  app/views/households/edit.html.erb:1:in `_app_views_households_edit_html_erb__1099396562214718293_70118538196100'
  app/controllers/households_controller.rb:76:in `update'
  lib/disable_tenant_scoping.rb:18:in `call'

_Originally created by **Tom Smyth** at **2017-06-27 21:25**, migrated from [redmine-#6735](https://redmine.sassafras.coop/issues/6735)_

**Comment by smoyth** [comment]
* **Status** changed from _New_ to _Closed_

_By **Tom Smyth** at **2017-06-29 17:53**_

**Comment by smoyth** [comment]
* **Version** set to _4.3_

_By **Tom Smyth** at **2017-07-06 16:30**_
