### ISSUE TITLE
Shift reminders not going to child users

### ISSUE THREAD

**Issue by smoyth** [gather-community/gather#328]
Add a spec ensuring this doesn't happen anymore

```
An ArgumentError occurred in background at 2017-05-05 06:00:10 -0400 :

  An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:9:in `check_delivery_params'

  -------------------------------
Backtrace:
-------------------------------

  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:9:in `check_delivery_params'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.3/lib/action_mailer/base.rb:543:in `block in deliver_mail'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.3/lib/action_mailer/base.rb:541:in `deliver_mail'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.3/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
  /u/apps/gather/releases/20170412020514/app/jobs/meals/shift_reminder_job.rb:23:in `block (2 levels) in perform'
  /u/apps/gather/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
```

_Originally created by **Tom Smyth** at **2017-05-05 09:16**, migrated from [redmine-#6409](https://redmine.sassafras.coop/issues/6409)_

**Comment by smoyth** [comment]
* **Description** updated ([diff](https://redmine.sassafras.coop/journals/24698/diff?detail_id=26180 "View differences"))
  *  **Estimate** set to _0.30 h_

_By **Tom Smyth** at **2017-06-09 11:27**_

**Comment by smoyth** [comment]
* **Priority** changed from _2_ to _1_

_By **Tom Smyth** at **2017-06-19 13:12**_

**Comment by smoyth** [comment]
* **Subject** changed from _Shift reminder sending to empty email address_ to _Shift reminders not going to child users_

_By **Tom Smyth** at **2017-06-29 05:36**_

**Comment by smoyth** [comment]
* **Status** changed from _New_ to _Closed_

_By **Tom Smyth** at **2017-07-06 16:17**_

**Comment by smoyth** [comment]
* **Version** set to _4.3_

_By **Tom Smyth** at **2017-07-06 16:30**_
