### ISSUE TITLE
InvalidAuthenticityToken on shift signup/unsignup

### ISSUE THREAD

**Issue by smoyth** [gather-community/gather#96]
Gather
Mon, Dec 10, 5:40 PM (10 days ago)
to gather.ops

An ActionController::InvalidAuthenticityToken occurred in shifts#signup:

  ActionController::InvalidAuthenticityToken
  lib/disable_tenant_scoping.rb:18:in `call'

-------------------------------
Request:
-------------------------------

  * URL        : https://touchstone.gather.coop/work/signups/1085/signup
  * HTTP Method: POST
  * IP address : 98.209.19.171
  * Parameters : {"controller"=>"work/shifts", "action"=>"signup", "id"=>"1085"}
  * Timestamp  : 2018-12-10 17:40:55 -0500
  * Server : ip-172-31-26-230
  * Rails root : /u/apps/gather/releases/20181209185429
  * Process: 1525

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"35f3fbe5c195be5a2bc7b8f471fa94ab",
   "user_return_to"=>"https://touchstone.gather.coop/work/signups/1085/signup",
   "warden.user.user.key"=>[[2692], ""],
   "lenses"=>
    {"version"=>4,
     "_global"=>{"period"=>"11", "choosee"=>"2692"},
     "work/shifts"=>
      {"index"=>{"shift"=>"open", "_path"=>"/work/signups?shift=open"}}},
   "_csrf_token"=>"3+ydJbh1SP6dfrt127z4DIxRYcC+/r+BFzmWqs4tGwE="}

-------------------------------
Environment:
-------------------------------

  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.9
  * HTTP_COOKIE                                    : [FILTERED]
  * HTTP_HOST                                      : touchstone.gather.coop
  * HTTP_ORIGIN                                    : https://touchstone.gather.coop
  * HTTP_REFERER                                   : https://touchstone.gather.coop/work/signups?search=&shift=open&period=11
  * HTTP_SAVE_DATA                                 : on
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_CSRF_TOKEN                              : [FILTERED]
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : /work/signups/1085/signup
  * ORIGINAL_SCRIPT_NAME                           : 
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PATH_INFO                                      : /work/signups/1085/signup
  * QUERY_STRING                                   : 
  * REMOTE_ADDR                                    : 98.209.19.171
  * REMOTE_PORT                                    : 46821
  * REQUEST_METHOD                                 : POST
  * REQUEST_URI                                    : /work/signups/1085/signup
  * ROUTES_47223148744800_SCRIPT_NAME              : 
  * SCRIPT_NAME                                    : 
  * SERVER_NAME                                    : touchstone.gather.coop
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.10.2 Phusion_Passenger/5.1.1
  * action_controller.instance                     : #<Work::ShiftsController:0x00007f2e6f85e4a0>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000055e5fa581de0>
  * action_dispatch.cookies                        : [FILTERED]
  * action_dispatch.cookies_digest                 : [FILTERED]
  * action_dispatch.cookies_serializer             : [FILTERED]
  * action_dispatch.encrypted_cookie_salt          : [FILTERED]
  * action_dispatch.encrypted_signed_cookie_salt   : [FILTERED]
  * action_dispatch.http_auth_salt                 : [FILTERED]
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x000055e60052aff8>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x000055e5fe1a2018>
  * action_dispatch.parameter_filter               : [:password, :session, :warden, :secret, :salt, :cookie, :csrf]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 98.209.19.171
  * action_dispatch.request.accepts                : [#<Mime::Type:0x00007f2e6f85c240 @synonyms=[], @symbol=nil, @string="*/*", @hash=16066036087090744>]
  * action_dispatch.request.formats                : [#<Mime::Type:0x00007f2e6f85c240 @synonyms=[], @symbol=nil, @string="*/*", @hash=16066036087090744>]
  * action_dispatch.request.parameters             : {"controller"=>"work/shifts", "action"=>"signup", "id"=>"1085"}
  * action_dispatch.request.path_parameters        : {:controller=>"work/shifts", :action=>"signup", :id=>"1085"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: [FILTERED]
  * action_dispatch.request_id                     : 41a2694b-43f5-4b1f-a2a5-1a58fb859bea
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000055e5fe0320c0>
  * action_dispatch.secret_key_base                : [FILTERED]
  * action_dispatch.secret_token                   : [FILTERED]
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : [FILTERED]
  * exception_notifier.exception_data              : {:community=>{:id=>1, :name=>"Touchstone"}, :user=>{:id=>2692, :name=>"Tom Idzikowski", :email=>"idzikowski.thomas@gmail.com", :google_email=>"idzikowski.thomas@gmail.com", :impersonating_id=>nil}}
  * rack.errors                                    : #<IO:0x000055e5f9379850>
  * rack.hijack                                    : #<Proc:0x00007f2e6f887e68@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00007f2e6f888110>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : [FILTERED]
  * rack.request.cookie_string                     : [FILTERED]
  * rack.request.form_hash                         : {}
  * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x00007f2e6f888110>
  * rack.request.form_vars                         : [FILTERED]
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      : 
  * rack.run_once                                  : false
  * rack.session                                   : [FILTERED]
  * rack.session.options                           : [FILTERED]
  * rack.tempfiles                                 : []
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : [FILTERED]

-------------------------------
Backtrace:
-------------------------------

  lib/disable_tenant_scoping.rb:18:in `call'

-------------------------------
Data:
-------------------------------

  * data: {:community=>{:id=>1, :name=>"Touchstone"},
   :user=>
    {:id=>2692,
     :name=>"Tom Idzikowski",
     :email=>"idzikowski.thomas@gmail.com",
     :google_email=>"idzikowski.thomas@gmail.com",
     :impersonating_id=>nil}}

_Originally created by **Tom Smyth** at **2018-12-20 09:56**, migrated from [redmine-#9230](https://redmine.sassafras.coop/issues/9230)_

**Comment by smoyth** [comment]
* **Version** set to _6.3_

_By **Tom Smyth** at **2018-12-26 21:13**_

**Comment by smoyth** [comment]
* **Status** changed from _New_ to _Closed_

_By **Tom Smyth** at **2019-03-01 21:53**_
